

services:

  api:
    container_name: subsentry_api
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  db:
    container_name: subsentry_db
    image: postgres:16.1
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subsentry_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: